### ISSUE TITLE
What feof() does

### ISSUE THREAD

**Issue by szepeviktor** [mnavarrocarter/php-fetch#13]
```php
        if (feof($this->resource)) {
            return null;
        }
        $result = @fread($this->resource, $bytes);
```

What does `feof` on HTTP level? How can it tell that the stream is over?
As I understand `fread` fires a new HTTP request each time. Am I wrong?

**Comment by szepeviktor** [comment]
https://www.php.net/manual/en/function.fread.php#example-2637 suggests to use https://www.php.net/manual/en/function.stream-get-contents

`stream_get_contents($this->resource, $bytes)`

**Comment by mnavarrocarter** [comment]
> What does feof on HTTP level? How can it tell that the stream is over?

It checks if the server has closed the connection. I think that's EOF in the http wrapper.

> As I understand fread fires a new HTTP request each time. Am I wrong?

It's actually `fopen` that does the request (gets the status line and headers). Then `resource` ends up containing just the response body. `fread` just reads of the resource. I think internally PHP resources do their own buffering.

**Comment by szepeviktor** [comment]
Okay.

I would gladly contribute to a test project that displays server and client (PHP HTTP stream) state to make this obvious.
